name: CI Maven Spring with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Chequear el código desde el repositorio
      - name: Check out the code
        uses: actions/checkout@v3

      # Paso 2: Instalar JDK (puedes cambiar la versión según tus necesidades)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Paso 3: Configurar SonarCloud (Es necesario tener el token en GitHub Secrets)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}    # Project key de SonarCloud
          organization: ${{ secrets.SONAR_ORGANIZATION }}  # Organización en SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          # Token de autenticación en SonarCloud

      # Paso 4: Ejecutar Maven para limpiar, compilar, ejecutar tests y analizar con SonarCloud
      - name: Build and Test with Maven
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
