name: CI Maven Spring with SonarCloud and PostgreSQL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Paso 1: Chequear el código desde el repositorio
      - name: Check out the code
        uses: actions/checkout@v3

      # Paso 2: Instalar JDK (puedes cambiar la versión según tus necesidades)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Paso 3: Esperar a que la base de datos esté lista
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done

      # Paso 4: Configurar SonarCloud (Es necesario tener el token en GitHub Secrets)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      # Paso 5: Configurar la base de datos PostgreSQL en el proyecto Spring
      - name: Set up PostgreSQL environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/testdb" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=testuser" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=testpassword" >> $GITHUB_ENV

      # Paso 6: Ejecutar Maven para limpiar, compilar, ejecutar tests y analizar con SonarCloud
      - name: Build and Test with Maven
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
